apiVersion: v1
kind: Service
metadata:
  name: tictactoe-service
spec:
  selector:
    app: tictactoe
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30000
